from typing import Any, Tuple

IMREAD_UNCHANGED: int
COLOR_BGR2GRAY: int
TM_CCORR_NORMED: int

def imread(filename: str, flags: int = ...) -> Any: ...
def imwrite(filename: str, img: Any) -> bool: ...
def cvtColor(src: Any, code: int) -> Any: ...
def matchTemplate(image: Any, templ: Any, method: int, mask: Any = ...) -> Any: ...
def minMaxLoc(src: Any) -> Tuple[float, float, Tuple[int, int], Tuple[int, int]]: ...


